import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import TimeAgo from 'react-timeago'
import UserColumn from "../components/UserColumn.js";
export default function Home(data) {
  const { countriesList } = data
  return (
    <div className="font-mono flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>DZGitrs - The most active GitHub users in </title>
        <meta name="viewport" content="width=device-width"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center flex-1 text-center">
        <h1 className="text-4xl font-bold lg:text-6xl">
          Welcome to{' '}
          <span className="text-green-600">
            DZGitrs!
          </span>
        </h1>
        

        <div className="flex flex-wrap items-center justify-around max-w-4xl mt-6 sm:w-full">
        { countriesList.length ? <ul className='text-left'>
             
            {
              countriesList.map(country=> (
                <li className='border-green-500 duration-200 ease-in-out	hover:border-l-4 hover:pl-2 '>
                  <Link href={country.slug}>{country.country}</Link>
                </li>
              ))
            }
          </ul> :'لا توجد احصائيات'  }
        </div>
      </main>

      <footer className="font-mono flex items-center flex-col justify-center w-full h-24 border-t text-center">
      <p className="my-5 text-1xl">
          <span className="text-lg bg-gray-100 rounded-md font-bold">
            Note:
          </span>
          <span>
            this list generated by <a href='https://commits.top/algeria.html'><b className='text-green-500'>commits.top</b></a>
          </span>
      </p>
      <p>
        <span className='pb-5 font-mono'><a href='https://dzgitrs.herokuapp.com/'>َAPI</a></span>
        <span>{' '}.{' '}</span>
        <span className='pb-5 font-mono'><a href='https://github.com/moncefplastin07/dzgitrs_app.vercel'>Github</a></span>
        <span>{' '}.{' '}</span>
        <span className='pb-5 font-mono'><a href='https://twitter.com/moncefplastin07/'>Twitter</a></span>
        <span>{' '}.{' '}</span>
        <span className='pb-5 font-mono'><a href='https://facebook.com/moncefplastin07/'>Facebook</a></span>
      </p>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch(`https://dzgitrs.herokuapp.com/get_countries`)
  const countriesList = await res.json()
  if (!countriesList) {
    return {
      notFound: true,
    }
  }

  return {
    props: { countriesList }, // will be passed to the page component as props
  }
}
